{{- if .Values.debug }}
apiVersion: v1
kind: Pod
metadata:
  name: nfs-debug
  namespace: {{ .Release.Namespace }}
spec:
  restartPolicy: Never
  containers:
    - name: debug
      image: alpine:3.19
      command: ["sh", "-c", "sleep infinity"]
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: mbtiles-pvc
{{- end }}
