apiVersion: v1
kind: PersistentVolume
metadata:
  name: mbtiles-pv
  namespace: {{ .Release.Namespace }}
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/lib/rancher/k3s/storage  # This maps to ~/.k3d/singletrail/data/ via k3d
    type: Directory
