apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mbtiles-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: mbtiles-pv


