apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mbtiles-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.storage }}
  storageClassName: ""
  volumeName: mbtiles-pv


