apiVersion: v1
kind: Secret
metadata:
  name: cf-origin-tls-test
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.secrets.tlsCert | b64enc }}
  tls.key: {{ .Values.secrets.tlsKey | b64enc }}
